x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  judge0_server:
    image: judge0/judge0:1.13.1
    env_file: judge0.conf
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - judge0_db
      - judge0_redis

  judge0_workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    env_file: judge0.conf
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - judge0_db
      - judge0_redis

  judge0_db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  judge0_redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

  app_db:
    image: postgres:16.2
    env_file: ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - app_data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

volumes:
  data:
  app_data:

networks:
  default:
    driver: bridge