x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  judge0_server:
    image: judge0/judge0:1.13.1
    env_file: judge0.conf
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - judge0_db
      - judge0_redis
      - judge0_workers

  judge0_workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    env_file: judge0.conf
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - judge0_db
      - judge0_redis

  judge0_db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - judge0_data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  judge0_redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

  app_db:
    image: postgres:16.2
    env_file: ./backend/.env
    volumes:
      - app_data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
  
  app_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: ./backend/.env
    depends_on:
      - judge0_server
      - app_db
  
  app_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file: ./frontend/.env
  
  nginx:
    image: nginx:1.27.1
    ports:
      - "3000:80" # Exposing Nginx on port 3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_backend
      - app_frontend

volumes:
  judge0_data:
  app_data:

networks:
  default:
    driver: bridge